import { useCallback, useEffect, useState } from "react";
import { api } from "../api";
import { Icon } from "../components/Icon";
import { ListSkeleton, TrackerTag } from "../components/UI";
import { deliveryMethodLabel, diagnosticStateClass, errorMessage, formatCoverageMinutes, formatDiagnosticDuration, relativeTime, trackerName } from "../format";
import { useI18n } from "../i18n";
import type { DiagnosticsResponse, Notify, TrackerKey } from "../types";

export function DiagnosticsPanel({ revision, notify }: { revision: number; notify: Notify }) {
  const { t, language } = useI18n();
  const [diagnostics, setDiagnostics] = useState<DiagnosticsResponse | null>(null), [tracker, setTracker] = useState<TrackerKey | "">(""), [outcome, setOutcome] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => {
    const query = new URLSearchParams({ limit: "100" });
    if (tracker) query.set("trackerKey", tracker);
    if (outcome) query.set("outcome", outcome);
    const result = await api<DiagnosticsResponse>(`/api/admin/diagnostics?${query}`, { signal });
    if (!signal?.aborted) setDiagnostics(result);
  }, [tracker, outcome]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal).catch((error) => { if (!controller.signal.aborted) notify(errorMessage(error), "bad"); }); return () => controller.abort(); }, [revision, load, notify]);
  const outcomes = [...new Set([...(diagnostics?.observations || []).map((row) => row.outcome), ...(outcome ? [outcome] : [])])].sort();
  return <>
    <section className="table-section diagnostic-section"><div className="section-heading"><div><h2>{t("Notification queue")}</h2><p>{t("Pending deliveries are persisted and retried automatically.")}</p></div></div>{!diagnostics ? <ListSkeleton /> : !diagnostics.notificationQueue?.length ? <div className="diagnostic-empty">{t("Queue is empty")}</div> : <div className="queue-table">{diagnostics.notificationQueue.map((row) => <div className="queue-row" key={row.id}><strong>{row.username}</strong><span>{t("Subscription {id}", { id: row.subscriptionId })}</span><span>{t("Attempts")}: {row.attempts}</span><span>{t("Next attempt")}: {relativeTime(row.nextAttemptAt)}</span><span className={`state ${diagnosticStateClass(row.status)}`}>{t(row.status)}</span><small>{row.lastError}</small></div>)}</div>}</section>
    <section className="table-section diagnostic-section"><div className="section-heading"><div><h2>{t("Tracker logs")}</h2><p>{t("Safe polling observations for investigating tracker behavior. Records expire after 168 hours.")}</p></div><div className="diagnostic-controls"><select aria-label={t("Filter logs by tracker")} value={tracker} onChange={(event) => setTracker(event.target.value as TrackerKey | "")}><option value="">{t("All trackers")}</option><option value="kinozal">Kinozal</option><option value="rutor">Rutor</option><option value="rutracker">RuTracker</option></select><select aria-label={t("Filter logs by outcome")} value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="">{t("All outcomes")}</option>{outcomes.map((value) => <option key={value} value={value}>{t(value)}</option>)}</select><button className="button button--quiet" onClick={() => void load().catch((error) => notify(errorMessage(error), "bad"))}><Icon name="refresh" />{t("Refresh")}</button></div></div>
      {!diagnostics ? <ListSkeleton /> : !diagnostics.observations.length ? <div className="diagnostic-empty">{t("No tracker observations match these filters.")}</div> : <div className="diagnostic-table"><div className="diagnostic-head"><span>{t("Observed")}</span><span>{t("Source")}</span><span>{t("Operation")}</span><span>{t("Outcome")}</span><span>{t("Details")}</span><span>{t("Duration")}</span></div>{diagnostics.observations.map((row) => {
        const url = row.resolvedUrl || row.requestedUrl, terms = typeof row.details.requiredTerms === "string" ? row.details.requiredTerms : undefined;
        const feedCount = numericDetail(row.details.feedEntryCount), feedBaseline = row.details.feedCoverageStatus === "baseline";
        const feedSummary = row.operation === "feed-poll" && feedCount !== undefined ? feedBaseline ? t("{count} feed entries seeded · overlap unavailable", { count: feedCount }) : [t("{count} feed entries scanned", { count: feedCount }), detailFragment(row.details.feedNewEntryCount, "new"), detailFragment(row.details.feedOverlapCount, "overlap")].filter(Boolean).join(" · ") : undefined;
        const ruleSummary = terms ? t("Rule evaluated: {terms}", { terms }) : undefined;
        const detail = row.title || ruleSummary || feedSummary || row.errorMessage || (row.releaseCount !== null && row.releaseCount !== undefined ? t("{count} releases observed", { count: row.releaseCount }) : t("Tracker request completed"));
        const coverage = row.operation === "feed-poll" ? numericDetail(row.details.feedCoverageMinutes) : undefined;
        const matched = numericDetail(row.details.matchedCount), newMatches = numericDetail(row.details.newMatchCount);
        const meta = [row.errorMessage, ruleSummary && matched !== undefined ? t("{count} matched", { count: matched }) : "", ruleSummary && newMatches !== undefined ? t("{count} new matches", { count: newMatches }) : "", coverage !== undefined ? t("{window} feed window", { window: formatCoverageMinutes(coverage) }) : "", row.httpStatus ? `HTTP ${row.httpStatus}` : "", row.externalId ? `ID ${row.externalId}` : ""].filter(Boolean).join(" · ");
        return <div className="diagnostic-row" key={row.id}><span className="diagnostic-time" title={new Date(row.observedAt).toLocaleString(language)}>{relativeTime(row.observedAt)}</span><span className="diagnostic-source"><TrackerTag tracker={row.trackerKey} /><span><strong>{trackerName(row.trackerKey)}</strong><small>{row.username}{row.subscriptionId ? ` · ${t("Subscription {id}", { id: row.subscriptionId })}` : ""}</small></span></span><span className="diagnostic-operation">{t(row.operation)}</span><span><span className={`state ${diagnosticStateClass(row.outcome)}`}>{t(row.outcome)}</span></span><span className="diagnostic-detail"><strong>{detail}</strong><small>{meta}</small>{url && <a href={url} target="_blank" rel="noreferrer">{url}</a>}</span><span className="diagnostic-duration">{formatDiagnosticDuration(row.durationMs)}</span></div>;
      })}</div>}
    </section>
    <section className="table-section diagnostic-section"><div className="section-heading"><div><h2>{t("Telegram deliveries")}</h2><p>{t("Delivery receipts and failures for subscription notifications. Records expire after 168 hours.")}</p></div></div>{!diagnostics ? <ListSkeleton /> : !diagnostics.telegramDeliveries.length ? <div className="diagnostic-empty">{t("No Telegram notifications have been attempted during the retention window.")}</div> : <div className="diagnostic-table diagnostic-table--telegram"><div className="diagnostic-head telegram-delivery-grid"><span>{t("Sent")}</span><span>{t("Account")}</span><span>{t("Source")}</span><span>{t("Delivery")}</span><span>{t("Outcome")}</span><span>{t("Release")}</span><span>{t("Duration")}</span></div>{diagnostics.telegramDeliveries.map((row) => {
      const detail = row.errorMessage || row.title || t("General notification"), receipt = row.telegramMessageId ? t("Telegram message #{id}", { id: row.telegramMessageId }) : t("No delivery receipt"), note = row.artworkErrorMessage ? t("Artwork fallback: {error} · {receipt}", { error: row.artworkErrorMessage, receipt }) : receipt;
      return <div className="diagnostic-row telegram-delivery-grid" key={row.id}><span className="diagnostic-time" title={new Date(row.createdAt).toLocaleString(language)}>{relativeTime(row.createdAt)}</span><span className="diagnostic-detail"><strong>{row.username}</strong><small>{row.subscriptionName || (row.subscriptionId ? t("Subscription {id}", { id: row.subscriptionId }) : t("Account message"))}</small></span><span className="diagnostic-source">{row.trackerKey ? <><TrackerTag tracker={row.trackerKey} /><span><strong>{trackerName(row.trackerKey)}</strong><small>{row.externalId ? `ID ${row.externalId}` : t("Release")}</small></span></> : <span><strong>{t("System")}</strong><small>Telegram</small></span>}</span><span className="diagnostic-operation">{deliveryMethodLabel(row.deliveryMethod)}</span><span><span className={`state ${diagnosticStateClass(row.outcome)}`}>{t(row.outcome)}</span></span><span className="diagnostic-detail"><strong title={detail}>{detail}</strong><small title={note}>{note}</small></span><span className="diagnostic-duration">{formatDiagnosticDuration(row.durationMs)}</span></div>;
    })}</div>}</section>
  </>;
  function detailFragment(value: unknown, label: string): string | undefined { const number = numericDetail(value); return number === undefined ? undefined : `${number} ${t(label)}`; }
}
function numericDetail(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) ? value : undefined; }
